### ISSUE TITLE
A record in Route53 isn't updated after pushing the new EC2 instance

### ISSUE THREAD

**Issue by Talgat777** [umotif-public/terraform-aws-bastion#15]
**What is the current behavior?**
Route53 isn't updating A record when Auto Scaling Group pushes the new EC2 instance

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Kill the EC2 process in Auto Scaling Group by setting desired capacity to 0 and then set it to 1 (min capacity should be set to 0)

**What is the expected behavior?**
After the new instance of EC2 is pushed, the A record in route53 should be updated with the latest EC2 public ip

**Software versions?**
-

**Comment by Ohid25** [comment]
Sincere apologies for the extremely late reply! We had some problems internally in our team.

Regarding your problem - does the EC2 instance have IAM permissions to allow for changing Route53 records?

```
data "aws_iam_policy_document" "bastion_role_policy" {
  count = var.hosted_zone_id != "" ? 1 : 0

  statement {
    actions = [
      "autoscaling:DescribeAutoScalingInstances",
      "autoscaling:DescribeAutoScalingGroups",
      "ec2:DescribeAddresses",
      "ec2:DescribeInstances",
      "ec2:DescribeTags"
    ]
    effect    = "Allow"
    resources = ["*"]
  }

  statement {
    actions = [
      "route53:ChangeResourceRecordSets",
      "route53:GetHostedZone"
    ]
    effect    = "Allow"
    resources = ["arn:${data.aws_partition.current.partition}:route53:::hostedzone/${var.hosted_zone_id}"]
  }
}
```
