### ISSUE TITLE
Allow schedules to be defined in zones other than Etc/UTC

### ISSUE THREAD

**Issue by ghost** [umotif-public/terraform-aws-bastion#16]
**What is the current behavior?**
Auto Scale Schedules are defined `Etc/UTC` timezone only

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug - feature request

**What is the expected behavior?**
The API allows us to define a local timezone so I'd like to do that in the module
https://aws.amazon.com/about-aws/whats-new/2021/03/amazon-ec2-auto-scaling-adds-support-for-local-time-zones-for-scheduled-scaling/

**Software versions?**
I had this requirement so I've forked the project and made a simple update. Would you like the addition as an MR?

**Comment by Ohid25** [comment]
That would be very much appreciated @MattBracewell-starstock if you can create a PR for the feature request 😁.

**Comment by Ohid25** [comment]
Thank you for the contribution @MattBracewell-starstock 🙌 ! This is now released as a part of [2.3.0](https://github.com/umotif-public/terraform-aws-bastion/releases/tag/2.3.0) release.
